/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebarsConfig can be generated from the filesystem, or explicitly defined here.

 Create as many sidebarsConfig as you want.
 */

// @ts-check
const path = require("path");
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebarsConfig = {
	// By default, Docusaurus generates a sidebar from the docs folder structure
	// tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

	// But you can create a sidebar manually
	JS: [
		{
			type: 'category',
			label: '源码笔记',
			items: ['js/webpack/index']
		}
	],
	JSWebpack5: [
		{
			type: 'category',
			label: 'WebPack',
			items: ['js/webpack/index']
		},
	],
	JSVue: [
		{
			type: 'category',
			label: 'VUE',
			items: ['js/vue/vue2', 'js/vue/vue3'],
		}
	],
	JSTypeScript: [
		{
			type: "category",
			label: "TypeScript",
			items: ['js/typescript/base', 'js/typescript/object']
		}
	],
	JSCodeDesign: [
		{
			type: "category",
			label: '前端工具库设计',
			items: ['js/design/package', 'js/design/package-ts', 'js/design/package-doc', 'js/design/package-test']
		}
	],

	JSNormal: [
		{
			type: 'autogenerated',
			dirName: "js/normal"
		}
	],
	// JS视频直播
	JSVideo: [
		{
			type: 'autogenerated',
			dirName: "js/video"
		}
	],
	JSWebpack3: [
		{
			type: 'autogenerated',
			dirName: "js/webpack3"
		}
	],
	Structure: [
		{
			type: "doc",
			id: 'structure/analyse',
			label: '算法分析',
		},
		{
			type: 'category',
			label: "线性结构",
			collapsed: true,
			items: [{
				type: 'category',
				label: "栈",
				collapsed: true,
				items: ['structure/linear01', 'structure/arrayStackImpl']
			}]
		},
		// {
		// 	type: 'category',
		// 	label: "非线性结构",
		// 	items: []
		// }
	],
	// StructureStack: [
	// 	{
	// 		type: 'category',
	// 		label: "栈",
	// 		items: ['structure/linear01', 'structure/arrayStackImpl']
	// 	}
	// ],
	Java: [
		{
			type: 'category',
			label: 'ORM',
			items: ['orm/mybatis/index'],
		},
	],
};

module.exports = sidebarsConfig;
